# Generated by Django 5.1.4 on 2024-12-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='google_place_id',
            field=models.CharField(default='asd', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafe',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafe',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
