# Generated by Django 5.1.4 on 2024-12-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_alter_cafe_address_alter_cafe_google_maps_uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='google_maps_uri',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
