# Generated by Django 5.1.4 on 2024-12-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_cafe_address_cafe_google_maps_uri_cafe_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
