# Generated by Django 5.1.4 on 2024-12-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_alter_cafe_address_alter_cafe_google_maps_uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='number_of_ratings',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='rating',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
