# Generated by Django 5.1.4 on 2024-12-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0004_cafe_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='number_of_ratings',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
