# Generated by Django 5.1.4 on 2024-12-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_rating_date_alter_review_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-rating__date']},
        ),
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
    ]
